ports:
- port: 8080
  onOpen: open-preview
- port: 8888
  onOpen: open-browser

vscode:
  extensions:
    - scala-lang.scala@0.3.8:wQBBM+lKILHBqOqlqW60xA==
    - scalameta.metals@1.7.2:ORs01tzkKl6fAKyhAExj+w==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==tasks:
  - command: sdk install sbt
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==